[package]
name = "sandbox_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "sandbox_rust"
path = "src/lib.rs"

[dependencies]
charming = { version = "0.3.1", features = ["ssr"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
